# .markdownlint.yml
default: true

MD013: false  # Allow long lines in documentation
MD033: false  # Allow inline HTML (for complex elements)
MD034: false  # Allow bare URLs (for links in documentation)

MD007:
  indent: 2   # 2-space indentation for lists