name: CI Basic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. ПРОВЕРКА GO ПРОЕКТА
  test-go:
    name: Test Go Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Initialize Go module if missing
      run: |
        if [ ! -f "relayer/go.mod" ]; then
          cd relayer
          go mod init github.com/dmsus/crossChainBridge/relayer
          go mod tidy
        fi
        
    - name: Build Go project
      run: |
        cd relayer
        go build -v ./...

  # 2. ПРОВЕРКА FOUNDRY КОНТРАКТОВ (НОВАЯ!)
  test-foundry:
    name: Test Foundry Contracts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    
    - name: Build contracts
      run: |
        cd contracts
        forge build
        
    - name: Run tests
      run: |
        cd contracts
        forge test

  # 3. ПРОВЕРКА MARKDOWN ДОКУМЕНТАЦИИ
  lint-markdown:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Markdown files exist
      run: |
        find . -name "*.md" -type f | head -10
        echo "Markdown files checked"

  # 4. БЕЗОПАСНОСТЬ - ТОЛЬКО ДЛЯ PULL REQUEST
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
        fi