name: CI Basic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 1. ПРОВЕРКА GO ПРОЕКТА (УПРОЩЕННАЯ)
  test-go:
    name: Test Go Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Initialize Go module if missing
      run: |
        if [ ! -f "relayer/go.mod" ]; then
          cd relayer
          go mod init github.com/dmsus/crossChainBridge/relayer
          go mod tidy
        fi
        
    - name: Build Go project
      run: |
        cd relayer
        go build -v ./...

  # 2. ПРОВЕРКА MARKDOWN ДОКУМЕНТАЦИИ (УПРОЩЕННАЯ)
  lint-markdown:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Markdown files exist
      run: |
        find . -name "*.md" -type f | head -10
        echo "Markdown files checked"

  # 3. БЕЗОПАСНОСТЬ - ТОЛЬКО ДЛЯ PULL REQUEST
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3

  # 4. ПОДГОТОВКА К SMART CONTRACTS (УСЛОВНАЯ)
  setup-node:
    name: Setup Node.js for future contracts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Check if contracts package exists
      run: |
        if [ -f "contracts/package.json" ]; then
          echo "package.json found - will install dependencies later"
        else
          echo "No package.json yet - this is expected at this stage"
        fi